name: deploy-book

on:
  push:
    branches:
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build the book
      run: |
        jupyter-book build example-book

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: example-book/_build/html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4